
set(CMAKE_THREAD_LIBS_INIT "-lpthread" CACHE STRING "")
set(CMAKE_HAVE_THREADS_LIBRARY ON CACHE BOOL "")
set(CMAKE_USE_WIN32_THREADS_INIT OFF CACHE BOOL "")
set(CMAKE_USE_PTHREADS_INIT ON CACHE BOOL "")
set(THREADS_PREFER_PTHREAD_FLAG ON CACHE BOOL "")
set(CMAKE_SYSTEM_NAME Windows CACHE STRING "")
set(CMAKE_SHARED_LIBRARY_SUFFIX .dll CACHE STRING "")

set(LLVM_BUILD_LLVM_DYLIB ON CACHE BOOL "")
set(LLVM_BUILD_LLVM_C_DYLIB OFF CACHE BOOL "")
set(LLVM_LINK_LLVM_DYLIB OFF CACHE BOOL "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
#set(LLVM_BUILD_STATIC ON CACHE BOOL "")
