
[build]
target = [ "hexagon-unknown-linux-musl"]

[target.hexagon-unknown-linux-musl]

linker = "hexagon-unknown-linux-musl-clang"
runner = "qemu-hexagon"
rustflags = ["-C", "target-cpu=hexagonv68"]

